
CREATE TABLE CRM_CLUBE_CLIENTE (
  CCL_ID INTEGER NOT NULL IDENTITY,
  CCL_TITULO VARCHAR(256) NOT NULL,
  CCL_OBSERVACAO VARCHAR(256)
);
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 1','OBS - CLUBE 1');
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 2','OBS - CLUBE 2');
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 3','OBS - CLUBE 3');

SELECT * from CRM_CLUBE_CLIENTE;

CREATE TABLE CRM_CRENCA_CLIENTE (
  CRC_ID INTEGER NOT NULL IDENTITY,
  CRC_TITULO VARCHAR(256) NOT NULL,
  CRC_OBSERVACAO VARCHAR(256),
  CRC_DICA_RELACIONAMENTO VARCHAR(256)
); 
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('CATÓLICO','RELIGIÃO','NAO DISCUTIR RELIGIAO');
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('PROTESTANTE','RELIGIÃO','NAO DISCUTIR RELIGIAO');
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('ATEU','RELIGIÃO','NAO DISCUTIR RELIGIAO');

SELECT * from CRM_CRENCA_CLIENTE;

CREATE TABLE CRM_ESPORTE_CLIENTE(
  ESP_ID INTEGER NOT NULL IDENTITY,
  ESP_TITULO VARCHAR(256) NOT NULL,
  ESP_OBSERVACAO VARCHAR(256)
); 

INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('FUTEBOL','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('BASQUETE','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('VOLEYBALL','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('JUDO','');

SELECT * from CRM_ESPORTE_CLIENTE;

CREATE TABLE CRM_ESTILO_CLIENTE(
  
  EST_ID INTEGER NOT NULL IDENTITY,
  EST_TITULO VARCHAR(256) NOT NULL,
  EST_OSERVACAO VARCHAR(256),
  EST_DICA_RELACIONAMENTO VARCHAR(256)
); 

INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('RIP','OBS - 1','PEACE N LOVE');
INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('ANARQUISTA','OBS - 2','POLICOS DE ESQUERDA');
INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('SOCIALITE','OBS - 3','CARROS DO ANO');

SELECT * from CRM_ESTILO_CLIENTE;


CREATE TABLE CRM_EMPRESAS
(
  EMP_ID INTEGER NOT NULL IDENTITY,
  EMP_NOME VARCHAR(15) NOT NULL,
  EMP_CAIXA_POSTAL VARCHAR(256),
  EMP_DDD VARCHAR(3),
  EMP_TELEFONE1 VARCHAR(8),
  EMP_TELEFONE2 VARCHAR(8),
  EMP_FAX VARCHAR(8),
  EMP_EMAIL VARCHAR(30),
  EMP_WEBSITE VARCHAR(30),
  EMP_CONDICAO_PAGAMENTO VARCHAR(50),
  EMP_OBSERVACAO VARCHAR(256),
  EMP_NUM_BENEFCIARIOS VARCHAR(3),
  EMP_PRODUTO VARCHAR(256),
  EMP_DATA_CONTRATO VARCHAR(10),
  EMP_BENEFICICIOS_AGREGADOS VARCHAR(256),
  EMP_PRECO VARCHAR(10),
  EMP_SUBSIDIA_PARA_FUNCIONARIO VARCHAR(10),
  EMP_VALOR_FATURA VARCHAR(10),
  EMP_QUALIFICACAO_MARGEM VARCHAR(256),
  EMP_DATA_ULTIMO_REAJUSTE VARCHAR(10),
  EMP_PORCENTAGEM_ULTIMO_REAJUSTE VARCHAR(3)
); 
INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('MERCEDES','13070280','019','32337093','FORNECEDOR','REVER');
INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('CHEVROLET','13070280','019','32337093','FORNECEDOR','REVER');
INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('FORD','13070280','019','32337093','FORNECEDOR','REVER');
SELECT * from CRM_EMPRESAS;

CREATE TABLE CRM_LAZER_CLIENTE
(
  LAZ_ID INTEGER NOT NULL IDENTITY,
  LAZ_TITULO VARCHAR(256)NOT NULL,
  LAZ_OBSERVACAO VARCHAR(256),
  LAZ_DICA_RELACIONAMENTO VARCHAR(256)
);

INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('AEROMODELISMO','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('KAIAQUE','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('LEGO','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('VELOCIDADE','','');

SELECT * FROM CRM_LAZER_CLIENTE;


CREATE TABLE CRM_PROFISSAO_CLIENTE
(
  PFC_ID INTEGER NOT NULL IDENTITY,
  PFC_TITULO VARCHAR(256),
  PFC_DIA_COMEMORATIVO VARCHAR(10),
  PFC_MES_COMEMORATIVO VARCHAR(10),
  PFC_OBSERVACAO VARCHAR(256),
  PFC_DCA_RELACIONAMENTO VARCHAR(256)
);
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('ENGENHEIRO','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('ANALISTA JR','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('DOMESTICA','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('VENDEDOR','10','01');

SELECT * from CRM_PROFISSAO_CLIENTE;

CREATE TABLE CRM_PRODUTO
(
  PRD_ID INTEGER NOT NULL IDENTITY,
  PRD_TITULO VARCHAR(256) NOT NULL,
  PRD_DESCRICAO VARCHAR(256),
  PRD_PRECO_UNIDADE VARCHAR(256)
); 


INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V600','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('E398','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V630','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V900','Celular Motorola');

SELECT * FROM CRM_PRODUTO;


CREATE TABLE CRM_TIPO_RELACAO
(
  TIR_ID INTEGER NOT NULL IDENTITY,
  TIR_TIPO_RELACAO VARCHAR(256),
  TIR_OBSERVACAO VARCHAR(256)
);

INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('FILHO','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('TIA','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('MAE','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('PAI','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('NETO','TIPO RELAÇÃO OBSERVAÇÃO');

SELECT * FROM CRM_TIPO_RELACAO;



CREATE TABLE CRM_CONTATO
(
  CNT_ID INTEGER NOT NULL IDENTITY,
  EMP_ID_FK INTEGER NOT NULL,
  LAZ_ID_FK INTEGER NOT NULL,
  ESP_ID_FK INTEGER NOT NULL,
  CCL_ID_FK INTEGER NOT NULL,
  CRC_ID_FK INTEGER NOT NULL,
  EST_ID_FK INTEGER NOT NULL,
  TIR_ID_FK INTEGER NOT NULL,
  PFC_ID_FK INTEGER NOT NULL,
  
  CNT_NOME VARCHAR(256),
  CNT_CHAMAR VARCHAR(256),
  CNT_SEXO VARCHAR(10),
  CNT_CIDADE_NASCIMENTO VARCHAR(50),
  CNT_UF_NASCIMENTO VARCHAR(2),
  CNT_ANIVERSARIO VARCHAR(10),
  CNT_DDD VARCHAR(3),
  CNT_TELEFONE VARCHAR(8),
  CNT_CELULAR VARCHAR(8),
  CNT_FAX VARCHAR(8),
  CNT_NEXTEL VARCHAR(8),
  CNT_EMAIL VARCHAR(30),
  CNT_CNT_ESTADO_CIVIL VARCHAR(20),
  CNT_DATA_CASAMENTO VARCHAR(10),
  CNT_FILHOS VARCHAR(2),
  CNT_NETOS VARCHAR(2),
  CNT_EMPRESA VARCHAR(256),
  CNT_CARGO VARCHAR(256),
  CNT_DEPARTAMENTO VARCHAR(256),
  CNT_RAMAL VARCHAR(10),
  CNT_SECRETARIA1 VARCHAR(256),
  CNT_SECRETARIA2 VARCHAR(256),
  CNT_LAZER VARCHAR(256),
  CNT_ESPORTE VARCHAR(256),
  CNT_CLUBE VARCHAR(256),
  CNT_CRENCA VARCHAR(256),
  CNT_ESTILO VARCHAR(256),
  CNT_PROFISSAO VARCHAR(256),
  CNT_TIPO_RELACAO VARCHAR(256),
  CNT_LOGRADOURO VARCHAR(256),
  CNT_NUMERO VARCHAR(10),
  CNT_COMPLEMENTO VARCHAR(50),
  CNT_BAIRO VARCHAR(50),
  CNT_CEP VARCHAR(15),
  CNT_CIDADE VARCHAR(50),
  CNT_UF VARCHAR(2),
    
  FOREIGN KEY (EMP_ID_FK) REFERENCES CRM_EMPRESAS(EMP_ID),  
  FOREIGN KEY (LAZ_ID_FK) REFERENCES CRM_LAZER_CLIENTE(LAZ_ID),
  FOREIGN KEY (ESP_ID_FK) REFERENCES CRM_ESPORTE_CLIENTE(ESP_ID),
  FOREIGN KEY (CCL_ID_FK) REFERENCES CRM_CLUBE_CLIENTE(CCL_ID),
  FOREIGN KEY (CRC_ID_FK) REFERENCES CRM_CRENCA_CLIENTE(CRC_ID),
  FOREIGN KEY (EST_ID_FK) REFERENCES CRM_ESTILO_CLIENTE(EST_ID),
  FOREIGN KEY (TIR_ID_FK) REFERENCES CRM_TIPO_RELACAO(TIR_ID),
  FOREIGN KEY (PFC_ID_FK) REFERENCES CRM_PROFISSAO_CLIENTE(PFC_ID)    
); 

INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'RODRIGO LUIS NOLLI BROSSI');
INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'RODRIGO ROCHA COSTA');
INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'CARLOS GARCIA');

SELECT * FROM CRM_CONTATO;

CREATE TABLE CRM_DATAS_COMEMORATIVAS
(
  DCM_ID INTEGER NOT NULL IDENTITY,
  
  LAZ_ID_FK INTEGER NOT NULL,
  ESP_ID_FK INTEGER NOT NULL,
  CRC_ID_FK INTEGER NOT NULL,
  CCL_ID_FK INTEGER NOT NULL,
  PFC_ID_FK INTEGER NOT NULL,
  
  DCM_TITULO VARCHAR(256),
  DCM_DATA_COMEMORACAO VARCHAR(256),
  DCM_SAUDACAO VARCHAR(256),
  DCM_INICIAR_SAUDACAO VARCHAR(256),
  DCM_TERMINAR_SAUDACAO VARCHAR(256),
  DCM_PERFIL_SEXO VARCHAR(256),
  DCM_PERFIL_FILHOS VARCHAR(256),
  DCM_PERFIL_NETOS VARCHAR(256),
  DCM_PROFISSAO VARCHAR(256),
  DCM_LAZER VARCHAR(256),
  DCM_ESPORTE VARCHAR(256),
  DCM_CLUBE VARCHAR(256),
  DCM_CRENCA VARCHAR(256),
    
  FOREIGN KEY (LAZ_ID_FK) REFERENCES CRM_LAZER_CLIENTE(LAZ_ID),
  FOREIGN KEY (ESP_ID_FK) REFERENCES CRM_ESPORTE_CLIENTE(ESP_ID),
  FOREIGN KEY (CRC_ID_FK) REFERENCES CRM_CRENCA_CLIENTE(CRC_ID),
  FOREIGN KEY (CCL_ID_FK) REFERENCES CRM_CLUBE_CLIENTE(CCL_ID),
  FOREIGN KEY (PFC_ID_FK) REFERENCES CRM_PROFISSAO_CLIENTE(PFC_ID)
); 

CREATE TABLE CRM_FILHOS
(
  FIL_ID INTEGER NOT NULL IDENTITY,
  
  CNT_ID_FK INTEGER NOT NULL,
  
  FIL_NOME VARCHAR(256),
  FIL_DATA_ANIVERSARIO VARCHAR(10),
  FIL_IDADE VARCHAR(2),  
  
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID)
); 

CREATE TABLE CRM_NETOS
(
  NET_ID INTEGER NOT NULL IDENTITY,
  
  CNT_ID_FK INTEGER NOT NULL,
  
  NET_NOME VARCHAR(256),
  NET_DATA_ANIVERSARIO VARCHAR(10),
  NET_IDADE VARCHAR(2),
    
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID)
);

CREATE TABLE CRM_USUARIOS
(
  USR_ID INTEGER NOT NULL IDENTITY,
  
  LAZ_ID_FK INTEGER NOT NULL,
  ESP_ID_FK INTEGER NOT NULL,
  CRC_ID_FK INTEGER NOT NULL,
  TIR_ID_FK INTEGER NOT NULL,
  PFC_ID_FK INTEGER NOT NULL,
  
  USR_NOME_USUARIO VARCHAR(256),
  USR_BENEFICIARIO_DESDE VARCHAR(10),
  USR_IS_ADMINISTRADOR BOOLEAN,
  USR_OPCADUSUARIOS VARCHAR(256),
  USR_OPCADCONTATOS VARCHAR(256),
  USR_OPCADEMPRESAS VARCHAR(256),
  USR_OPCADRAMOSATIVIDADES VARCHAR(256),
  USR_OPCADESTILOSCLIENTES VARCHAR(256),
  USR_OPCADCRENCAS VARCHAR(256),
  USR_OPCADESPORTES VARCHAR(256),
  USR_OPCADCLUBES VARCHAR(256),
  USR_OPCADLAZARES VARCHAR(256),
  USR_OPCADPROFISSOES VARCHAR(256),
  USR_OPCADDATASCOMEMORATIVAS VARCHAR(256),
  USR_OPCADMENSRELACIONAMENTO VARCHAR(256),
  USR_OPCADTIPORELACAO VARCHAR(256),
  USR_ULTIMOACESSO VARCHAR(10),
  USR_ANIVERSARIO VARCHAR(10),
  USR_SEXO VARCHAR(1),
  USR_FILHOS VARCHAR(2),
  USR_LAZER VARCHAR(256),
  USR_ESPORTE VARCHAR(256),
  USR_PROFISSAO VARCHAR(256),
  USR_CARGO_FUNCAO VARCHAR(256),
  USR_DATA_ADMISSAO VARCHAR(10),
  USR_SENHA_USUARIO VARCHAR(8),
  USR_REFAZER_SENHA VARCHAR(8),
  
  FOREIGN KEY (LAZ_ID_FK) REFERENCES CRM_LAZER_CLIENTE(LAZ_ID),
  FOREIGN KEY (ESP_ID_FK) REFERENCES CRM_ESPORTE_CLIENTE(ESP_ID),
  FOREIGN KEY (CRC_ID_FK) REFERENCES CRM_CRENCA_CLIENTE(CRC_ID),
  FOREIGN KEY (TIR_ID_FK) REFERENCES CRM_TIPO_RELACAO(TIR_ID),
  FOREIGN KEY (PFC_ID_FK) REFERENCES CRM_PROFISSAO_CLIENTE(PFC_ID)
);

INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'RBROSSI','KAZU99');
INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'RCOSTA','RCOSTA');
INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'CAPGARCIA','CAPGARCIA');


CREATE TABLE CRM_HISTORICO_CONTATO
(
  HIS_ID INTEGER NOT NULL IDENTITY,
  
  CNT_ID_FK INTEGER NOT NULL,
  USR_ID_FK INTEGER NOT NULL,
  
  HIS_RESUMO VARCHAR(256),
  HIS_DATA VARCHAR(10),
  HIS_PENDENTE VARCHAR(256),
  HIS_ALERTA VARCHAR(256),
  HIS_FEEDBACK_USUARIO VARCHAR(256),
          
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID),
  FOREIGN KEY (USR_ID_FK) REFERENCES CRM_USUARIOS(USR_ID)
); 

CREATE TABLE CRM_RELACIONAMENTO
(
  MER_ID INTEGER NOT NULL IDENTITY,
  
  LAZ_ID_FK INTEGER NOT NULL,
  ESP_ID_FK INTEGER NOT NULL,
  CRC_ID_FK INTEGER NOT NULL,
  CCL_ID_FK INTEGER NOT NULL,
  PFC_ID_FK INTEGER NOT NULL,
  
  MER_TITULO VARCHAR(256),
  MER_MENSAGEM VARCHAR(256),
  MER_EXCLUIR_MSGS BOOLEAN,
  MER_DATA_INICIAR VARCHAR(10),
  MER_DATA_TERMINAR VARCHAR(10),
  MER_PERFIL_SEXO VARCHAR(50),
  MER_PERFIL_FILHOS VARCHAR(50),
  MER_PERFIL_NETOS VARCHAR(50),
  MER_LAZER VARCHAR(256),
  MER_ESPORTE VARCHAR(256),
  MER_CLUBE VARCHAR(256),
  MER_CRENCA VARCHAR(256),
  MER_PROFISSAO VARCHAR(256),
  MER_USUARIOS_VIEW VARCHAR(256),
  MER_IDADE_FAIXA_ETARIA VARCHAR(256),
  MER_NATURALIDADE VARCHAR(256),
  MER_CIDADE_ONDE_MORA VARCHAR(256),
  MER_BAIRRO_ONDE_MORA VARCHAR(256),
  MER_FAIXA_CEP_ONDE_MORA VARCHAR(20),
  MER_EMPRESA_QUE_TRABALHA VARCHAR(256),
  MER_CARGO_EXERCIDO VARCHAR(256),
  MER_TEMPO_NA_EMPRESA VARCHAR(10),
  MER_ESTADO_CIVIL VARCHAR(20),
  MER_TEL_EMPRESA BOOLEAN,
  MER_TEL_RESIDENCIAL BOOLEAN,
  MER_TEL_CELULAR BOOLEAN,
  MER_FAX BOOLEAN,
  MER_END_COMPLETO BOOLEAN,
  MER_EMAIL BOOLEAN,
  MER_TEMPO_COMO_BENEFICIARIO VARCHAR(2),
    
  FOREIGN KEY (LAZ_ID_FK) REFERENCES CRM_LAZER_CLIENTE(LAZ_ID),
  FOREIGN KEY (ESP_ID_FK) REFERENCES CRM_ESPORTE_CLIENTE(ESP_ID),
  FOREIGN KEY (CRC_ID_FK) REFERENCES CRM_CRENCA_CLIENTE(CRC_ID),
  FOREIGN KEY (CCL_ID_FK) REFERENCES CRM_CLUBE_CLIENTE(CCL_ID),
  FOREIGN KEY (PFC_ID_FK) REFERENCES CRM_PROFISSAO_CLIENTE(PFC_ID)
);

CREATE TABLE CRM_PREMIACOES
(
  PRM_ID INTEGER NOT NULL IDENTITY,
  PRM_DESCRICAO VARCHAR(256),
  PRM_QUANTIDADE VARCHAR(256),
  PRM_QUALIFICACAO_VENDAO VARCHAR(256),
  PRM_FORMA_PAGAMENTO VARCHAR(256),
  PRM_DATA1 VARCHAR(10),
  PRM_DATA2 VARCHAR(10),
  PRM_MENSAGEM VARCHAR(256)
); 

CREATE TABLE CRM_PROVIDENCIAS
(
  PRV_ID INTEGER NOT NULL IDENTITY,
  
  USR_ID_FK INTEGER NOT NULL,
  CNT_ID_FK INTEGER NOT NULL,
  
  PRV_PROVIDENCIAR VARCHAR(256),
  PRV_PARA_QUANDO VARCHAR(10),
  PRV_QUEM_DEVE_PROVIDENCIAR VARCHAR(256),
  PRV_QUEM_ESTA_NOTANDO VARCHAR(256),
  PRV_QUEM_ESTA_AGUARDANDO VARCHAR(256),

  FOREIGN KEY (USR_ID_FK) REFERENCES CRM_USUARIOS(USR_ID),
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID)
);


CREATE TABLE CRM_RAMO_ATIVIDADE
(
  RAT_ID INTEGER NOT NULL IDENTITY,
  RAT_TITULO VARCHAR(256),
  RAT_OBSERVACAO VARCHAR(256)
);

INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('RURAL','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('VENDAS','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('METALURGICA','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('SOFTWARE','RAMO DE ATIVIDADE');


CREATE TABLE CRM_REGISTRO_VISITA
(
  RGV_ID INTEGER NOT NULL IDENTITY,
  
  EMP_ID_FK INTEGER NOT NULL,
  CNT_ID_FK INTEGER NOT NULL,
  
  RGV_TIPO_VISITA VARCHAR(256),
  RGV_DATA_VISITA VARCHAR(10),
  RGV_QUEM_VISITOU VARCHAR(256),
  RGV_MOTIVO VARCHAR(256),
  RGV_RESULTADO VARCHAR(256),
  RGV_OBSERVACAO VARCHAR(256),
  RGV_VISITA_REALIZADA VARCHAR(10),
  RGV_VISITA_RECEBIDA VARCHAR(10),

  FOREIGN KEY (EMP_ID_FK) REFERENCES CRM_EMPRESAS(EMP_ID),
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID)
);


CREATE TABLE CRM_VENDAS
(
  VND_ID INTEGER NOT NULL IDENTITY,
  
  CNT_ID_FK INTEGER NOT NULL,
  USR_ID_FK INTEGER NOT NULL,
  PRD_ID_FK INTEGER NOT NULL,

  VND_VENDEDOR VARCHAR(256),  
  VND_CONTATO VARCHAR(256),  
  VND_PRODUTO VARCHAR(256),
  VND_NUMERO_VIDAS VARCHAR(256),
  VND_CLASSIFICACAO VARCHAR(256),
  VND_USUARIO VARCHAR(256),

  FOREIGN KEY (USR_ID_FK) REFERENCES CRM_USUARIOS(USR_ID),
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID),
  FOREIGN KEY (PRD_ID_FK) REFERENCES CRM_PRODUTO(PRD_ID)
);




CREATE TABLE CRM_VENDEDORES
(
  VNR_ID INTEGER NOT NULL IDENTITY,    
  
  VNR_VENDEDOR VARCHAR(256) NOT NULL,
  VNR_DATA_ADMISSAO VARCHAR(10),
  VNR_OBSERVACAO VARCHAR(500),
  VNR_SENHA_VENDA VARCHAR(8)
);



CREATE TABLE CRM_HISTORICO_CONTATO
(
  HIS_ID INTEGER NOT NULL IDENTITY,
  
  CNT_ID_FK INTEGER NOT NULL,
  USR_ID_FK INTEGER NOT NULL,
  
  HIS_RESUMO VARCHAR(256),
  HIS_DATA VARCHAR(10),
  HIS_PENDENTE VARCHAR(256),
  HIS_ALERTA VARCHAR(256),
  HIS_FEEDBACK_USUARIO VARCHAR(256),
          
  FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID),
  FOREIGN KEY (USR_ID_FK) REFERENCES CRM_USUARIOS(USR_ID)
);


