CREATE SEQUENCE typebarsq;
CREATE TABLE TYPEBAR
(
	TYP_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('typebarsq'),
	TYP_NAME VARCHAR(256),
	TYP_DESCRIPTION VARCHAR(256)
);
GRANT ALL ON TABLE TYPEBAR TO public;
CREATE SEQUENCE clientsq;
CREATE TABLE CLIENT
(
	CLI_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('clientsq'),
	CLI_NAME VARCHAR(256),
	CLI_PHONE VARCHAR(256),
	CLI_CEP	VARCHAR(256)

);
GRANT ALL ON TABLE CLIENT TO public;
CREATE SEQUENCE controlsq;
CREATE TABLE CONTROL
(
	CTR_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('controlsq'),
	CLI_ID_FK INTEGER NOT NULL,
	CTR_TABLE INTEGER,
	CTR_CARD  INTEGER,
	
	FOREIGN KEY (CLI_ID_FK) REFERENCES CLIENT(CLI_ID)
	
);
CREATE SEQUENCE dirnkssq;
CREATE TABLE DRINK(
	DRK_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('dirnkssq'),
	TYP_ID_FK INTEGER NOT NULL,
	DRK_PRICE FLOAT,
	DRK_NAME VARCHAR(256),
	DRK_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GRANT ALL ON TABLE DRINK TO public;
CREATE SEQUENCE foodsq;
CREATE TABLE FOOD(
	FOO_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('foodsq'),
	TYP_ID_FK INTEGER NOT NULL,
	FOO_PRICE FLOAT,
	FOO_NAME VARCHAR(256),
	FOO_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GRANT ALL ON TABLE FOOD TO public;
CREATE SEQUENCE suplementalssq;
CREATE TABLE SUPLEMENTALS(
	SUP_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('suplementalssq'),
	TYP_ID_FK INTEGER NOT NULL,
	SUP_PRICE FLOAT,
	SUP_NAME VARCHAR(256),
	SUP_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GRANT ALL ON TABLE SUPLEMENTALS TO public;
CREATE SEQUENCE credentialssq;
CREATE TABLE CREDENTIALS
(
	CRD_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('credentialssq'), 
	CRD_NAME VARCHAR(8)
);
GRANT ALL ON TABLE CREDENTIALS TO public;
CREATE SEQUENCE barusersq;
CREATE TABLE BARUSER
(
	USR_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('barusersq'),
	USR_LOGIN VARCHAR(256),
	USR_PASSWORD VARCHAR(256),
	CRD_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (CRD_ID_FK) REFERENCES CREDENTIALS(CRD_ID)
);
GRANT ALL ON TABLE BARUSER TO public;
INSERT INTO CREDENTIALS(CRD_NAME) VALUES ('ADMIN');
INSERT INTO CREDENTIALS(CRD_NAME) VALUES ('USER');
INSERT INTO BARUSER(USR_LOGIN,USR_PASSWORD,CRD_ID_FK) VALUES('ADMIN','ADMIN',(SELECT CRD_ID FROM CREDENTIALS WHERE CRD_NAME = 'ADMIN'));

CREATE SEQUENCE productssq;
CREATE TABLE PRODUCTS
(
	PRO_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('productssq'),
	CTR_ID_FK INTEGER NOT NULL,
	TYP_ID_FK INTEGER,
	PRO_NAME VARCHAR(256),
	
	FOREIGN KEY (CTR_ID_FK) REFERENCES CREDENTIALS(CRD_ID),
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GRANT ALL ON TABLE PRODUCTS TO public;
CREATE SEQUENCE food_productsq;
CREATE TABLE FOOD_PRODUCTS
(
	FPR_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('food_productsq'),
	PRO_ID_FK INTEGER NOT NULL,
	FOO_ID_FK INTEGER NOT NULL,
	SUP_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (PRO_ID_FK) REFERENCES PRODUCTS(PRO_ID),
	FOREIGN KEY (FOO_ID_FK) REFERENCES FOOD(FOO_ID),
	FOREIGN KEY (SUP_ID_FK) REFERENCES SUPLEMENTALS(SUP_ID)
);
GRANT ALL ON TABLE FOOD_PRODUCTS TO public;
CREATE SEQUENCE drink_productsq;
CREATE TABLE DRINK_PRODUCTS
(
	DPR_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('drink_productsq'),
	PRO_ID_FK INTEGER NOT NULL,
	DRK_ID_FK INTEGER NOT NULL,
	SUP_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (PRO_ID_FK) REFERENCES PRODUCTS(PRO_ID),
	FOREIGN KEY (DRK_ID_FK) REFERENCES DRINK(DRK_ID),
	FOREIGN KEY (SUP_ID_FK) REFERENCES SUPLEMENTALS(SUP_ID)
);
GRANT ALL ON TABLE DRINK_PRODUCTS TO public;
GRANT ALL ON DATABASE seujeito TO public;




