USE master
CREATE LOGIN ADMIN 
	WITH PASSWORD = 'ADMIN123';
GO
CREATE DATABASE DBADMIN01
ON 
( NAME = prods_dat,
   FILENAME = 'c:\seujeito\prods.mdf', /*Path do banco*/
   SIZE = 4,
   MAXSIZE = 10,
   FILEGROWTH = 1 )
GO
USE [DBADMIN01]
GO
CREATE USER [ADMIN] FOR LOGIN [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_accessadmin] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_securityadmin] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_backupoperator] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_ddladmin] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_datareader] TO [ADMIN]
GO
USE [DBADMIN01]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_datawriter] TO [ADMIN]
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_owner', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_backupoperator', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_datawriter', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_accessadmin', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_ddladmin', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_securityadmin', N'ADMIN'
GO
USE [DBADMIN01]
GO
EXEC sp_addrolemember N'db_datareader', N'ADMIN'
GO
USE [DBADMIN01]
GO
CREATE TABLE TYPEBAR
(
	TYP_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TYP_NAME VARCHAR(256),
	TYP_DESCRIPTION VARCHAR(256)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE CLIENT
(
	CLI_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CLI_NAME VARCHAR(256),
	CLI_PHONE VARCHAR(256),
	CLI_CEP	VARCHAR(256)

);
GO
USE [DBADMIN01]
GO
CREATE TABLE CONTROL
(
	CTR_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CLI_ID_FK INTEGER NOT NULL,
	CTR_TABLE INTEGER,
	CTR_CARD  INTEGER,
	
	FOREIGN KEY (CLI_ID_FK) REFERENCES CLIENT(CLI_ID)
	
);
GO
USE [DBADMIN01]
GO
CREATE TABLE DRINK(
	DRK_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TYP_ID_FK INTEGER NOT NULL,
	DRK_PRICE FLOAT,
	DRK_NAME VARCHAR(256),
	DRK_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE FOOD(
	FOO_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TYP_ID_FK INTEGER NOT NULL,
	FOO_PRICE FLOAT,
	FOO_NAME VARCHAR(256),
	FOO_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE SUPLEMENTALS(
	SUP_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TYP_ID_FK INTEGER NOT NULL,
	SUP_PRICE FLOAT,
	SUP_NAME VARCHAR(256),
	SUP_DESCRIPTION VARCHAR(256),
	
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE CREDENTIALS
(
	CRD_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	CRD_NAME VARCHAR(8)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE BARUSER
(
	USR_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	USR_LOGIN VARCHAR(256),
	USR_PASSWORD VARCHAR(256),
	CRD_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (CRD_ID_FK) REFERENCES CREDENTIALS(CRD_ID)
);
GO
USE [DBADMIN01]
GO
INSERT INTO CREDENTIALS(CRD_NAME) VALUES ('ADMIN');
INSERT INTO CREDENTIALS(CRD_NAME) VALUES ('USER');
INSERT INTO BARUSER(USR_LOGIN,USR_PASSWORD,CRD_ID_FK) VALUES('ADMIN','ADMIN',(SELECT CRD_ID FROM CREDENTIALS WHERE CRD_NAME = 'ADMIN'));
GO
USE [DBADMIN01]
GO
CREATE TABLE PRODUCTS
(
	PRO_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	CTR_ID_FK INTEGER NOT NULL,
	TYP_ID_FK INTEGER,
	PRO_NAME VARCHAR(256),
	
	FOREIGN KEY (CTR_ID_FK) REFERENCES CREDENTIALS(CRD_ID),
	FOREIGN KEY (TYP_ID_FK) REFERENCES TYPEBAR(TYP_ID)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE FOOD_PRODUCTS
(
	FPR_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PRO_ID_FK INTEGER NOT NULL,
	FOO_ID_FK INTEGER NOT NULL,
	SUP_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (PRO_ID_FK) REFERENCES PRODUCTS(PRO_ID),
	FOREIGN KEY (FOO_ID_FK) REFERENCES FOOD(FOO_ID),
	FOREIGN KEY (SUP_ID_FK) REFERENCES SUPLEMENTALS(SUP_ID)
);
GO
USE [DBADMIN01]
GO
CREATE TABLE DRINK_PRODUCTS
(
	DPR_ID INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PRO_ID_FK INTEGER NOT NULL,
	DRK_ID_FK INTEGER NOT NULL,
	SUP_ID_FK INTEGER NOT NULL,
	
	FOREIGN KEY (PRO_ID_FK) REFERENCES PRODUCTS(PRO_ID),
	FOREIGN KEY (DRK_ID_FK) REFERENCES DRINK(DRK_ID),
	FOREIGN KEY (SUP_ID_FK) REFERENCES SUPLEMENTALS(SUP_ID)
);


insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Rodrigo Luis Nolli Brossi','13035-000','1932673386');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Thiago Luis Nolli Brossi','13035-100','19326735560');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Juliana Del Tio Brossi','13035-000','1932673386');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Daniel Lopes','13035-728','1932337093');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Fabiana Brossi Lopes','13035-728','1932337093');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Luiz Carlos Brossi','13035-728','1932337093');
insert into CLIENT(CLI_NAME,CLI_CEP,CLI_PHONE) values ('Delciara Maria Nolli Brossi','13035-728','1932337093');

