CREATE TABLE RSD_KPIMAP
(
  KPI_ID INTEGER NOT NULL PRIMARY KEY,
  KPI_SECTOR	VARCHAR(256),
  KPI_CREATION  DATE,
  KPI_NAME	VARCHAR(256),
  KPI_VALUE	VARCHAR(256),
  KPI_TARGET	VARCHAR(256),
  KPI_VALUE_TYPE 	VARCHAR(256),
  KPI_MAX_VALUE	VARCHAR(256),
  KPI_MIN_VALUE VARCHAR(256),
  KPI_SOURCE VARCHAR(256),
  KPI_CODE VARCHAR(256)
);

  /*CNT_ID_FK INTEGER NOT NULL,
  USR_ID_FK INTEGER NOT NULL,*/

          
  /*FOREIGN KEY (CNT_ID_FK) REFERENCES CRM_CONTATO(CNT_ID),
  FOREIGN KEY (USR_ID_FK) REFERENCES CRM_USUARIOS(USR_ID)*/


create sequence rsd_kpimap_seq
    start 1
    increment 1
    NO MAXVALUE
    CACHE 1;
ALTER TABLE rds_kpimap
OWNER TO postgres;
/*nextval('rsd_kpimap_seq')*/
