/*Insert into clube clientte*/
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 1','OBS - CLUBE 1');
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 2','OBS - CLUBE 2');
INSERT INTO CRM_CLUBE_CLIENTE(CCL_TITULO,CCL_OBSERVACAO) VALUES ('CLUBE 3','OBS - CLUBE 3');
/*Insert into cresca cliente*/
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('CATÓLICO','RELIGIÃO','NAO DISCUTIR RELIGIAO');
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('PROTESTANTE','RELIGIÃO','NAO DISCUTIR RELIGIAO');
INSERT INTO CRM_CRENCA_CLIENTE(CRC_TITULO,CRC_OBSERVACAO,CRC_DICA_RELACIONAMENTO) VALUES ('ATEU','RELIGIÃO','NAO DISCUTIR RELIGIAO');
/*Insert into esporte*/
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('FUTEBOL','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('BASQUETE','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('VOLEYBALL','');
INSERT INTO CRM_ESPORTE_CLIENTE(ESP_TITULO,ESP_OBSERVACAO) VALUES ('JUDO','');

INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('RIP','OBS - 1','PEACE N LOVE');
INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('ANARQUISTA','OBS - 2','POLICOS DE ESQUERDA');
INSERT INTO CRM_ESTILO_CLIENTE(EST_TITULO,EST_OSERVACAO,EST_DICA_RELACIONAMENTO) VALUES ('SOCIALITE','OBS - 3','CARROS DO ANO');

INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('MERCEDES','13070280','019','32337093','FORNECEDOR','REVER');
INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('CHEVROLET','13070280','019','32337093','FORNECEDOR','REVER');
INSERT INTO CRM_EMPRESAS (EMP_NOME,EMP_CAIXA_POSTAL,EMP_DDD, EMP_TELEFONE1,EMP_OBSERVACAO,EMP_PRODUTO)
    VALUES('FORD','13070280','019','32337093','FORNECEDOR','REVER');

INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('AEROMODELISMO','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('KAIAQUE','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('LEGO','','');
INSERT INTO CRM_LAZER_CLIENTE(LAZ_TITULO,LAZ_OBSERVACAO,LAZ_DICA_RELACIONAMENTO)VALUES('VELOCIDADE','','');


INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('ENGENHEIRO','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('ANALISTA JR','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('DOMESTICA','10','01');
INSERT INTO CRM_PROFISSAO_CLIENTE(PFC_TITULO,PFC_DIA_COMEMORATIVO,PFC_MES_COMEMORATIVO)VALUES('VENDEDOR','10','01');

INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V600','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('E398','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V630','Celular Motorola');
INSERT INTO CRM_PRODUTO(PRD_TITULO,PRD_DESCRICAO) VALUES ('V900','Celular Motorola');

INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('FILHO','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('TIA','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('MAE','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('PAI','TIPO RELAÇÃO OBSERVAÇÃO');
INSERT INTO CRM_TIPO_RELACAO(TIR_TIPO_RELACAO,TIR_OBSERVACAO) VALUES ('NETO','TIPO RELAÇÃO OBSERVAÇÃO');

INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'RODRIGO LUIS NOLLI BROSSI');
INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'RODRIGO ROCHA COSTA');
INSERT INTO CRM_CONTATO(EMP_ID_FK,LAZ_ID_FK,ESP_ID_FK,CCL_ID_FK,CRC_ID_FK,EST_ID_FK,TIR_ID_FK,PFC_ID_FK,CNT_NOME)
VALUES (0,0,0,0,0,0,0,0,'CARLOS GARCIA');


INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'RBROSSI','KAZU99');
INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'RCOSTA','RCOSTA');
INSERT INTO CRM_USUARIOS(LAZ_ID_FK,ESP_ID_FK,CRC_ID_FK,TIR_ID_FK,PFC_ID_FK,USR_NOME_USUARIO,USR_SENHA_USUARIO)
VALUES(0,0,0,0,0,'CAPGARCIA','CAPGARCIA');


INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('RURAL','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('VENDAS','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('METALURGICA','RAMO DE ATIVIDADE');
INSERT INTO CRM_RAMO_ATIVIDADE(RAT_TITULO,RAT_OBSERVACAO) VALUES ('SOFTWARE','RAMO DE ATIVIDADE');
